---
- name: Update apt cache if needed
  become: yes
  apt: update_cache=yes cache_valid_time=86400

- name: Verify that the deployment key in deployment_key is present
  copy:
    src: "{{ deployment_key }}"
    dest: ~/.ssh/deployment
    mode: 0400
  when: deployment_key is defined
- name: Verify that the deployment key is present
  copy:
    src: ~/.ssh/deployment
    dest: ~/.ssh/deployment
    mode: 0400
  when: deployment_key is undefined

- include_vars: system_requirements.yml

- name: Install system packages
  become: yes
  apt: name={{ item }} state=present
  with_items: "{{ system_requirements }}"

- name: add somaxconn
  become: yes
  command: sysctl -w net.core.somaxconn=1024

- name: add somaxconn to sysctl to make it permanent
  become: yes
  lineinfile:
    name: /etc/sysctl.conf
    line: 'net.core.somaxconn=1024'
